AWSTemplateFormatVersion: 2010-09-09
Description: document-processing
Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 128
    Handler: index.handler
    Architectures:
      - arm64
    Layers:
      - !Ref LambdaPowertoolsLayer

Resources:
  InputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  OutputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DocumentTextDetectionCompletedTopic:
    Type: AWS::SNS::Topic

  DocumentTextDetectionCompletedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - textract.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - !Ref DocumentTextDetectionCompletedTopic
          PolicyName: DocumentTextDetectionCompletedPolicy

  LambdaPowertoolsLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: nodejs18.x
    Properties:
      LayerName: lambda-powertools-layer
      ContentUri: layers/lambda-powertools
      CompatibleRuntimes:
        - nodejs18.x

  StartDocumentTextDetectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/start-document-text-detection
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - textract:StartDocumentTextDetection
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:GetObjectTagging
                - s3:PutObjectTagging
                - s3:GetObjectVersion
              Resource: !Sub ${InputS3Bucket.Arn}/*
      Environment:
        Variables:
          DOCUMENT_TEXT_DETECTION_COMPLETED_SNS_TOPIC: !Ref DocumentTextDetectionCompletedTopic
          DOCUMENT_TEXT_DETECTION_COMPLETED_SNS_TOPIC_ROLE: !GetAtt DocumentTextDetectionCompletedRole.Arn
      Events:
        StateChange:
          Type: EventBridgeRule
          Properties:
            EventBusName: default
            Pattern:
              source:
                - aws.s3
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                    - !Ref InputS3Bucket
                object:
                  key:
                    - suffix: .pdf

  DocumentTextDetectionCompletedHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/document-text-detection-completed-handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - textract:GetDocumentTextDetection
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:GetObjectTagging
                - s3:PutObjectTagging
              Resource:
                - !GetAtt InputS3Bucket.Arn
                - !Sub ${InputS3Bucket.Arn}/*
                - !GetAtt OutputS3Bucket.Arn
                - !Sub ${OutputS3Bucket.Arn}/*
      Events:
        DocumentTextDetectionCompletedHandlerEvent:
          Type: SNS
          Properties:
            Topic:
              !Ref DocumentTextDetectionCompletedTopic
      Environment:
        Variables:
          OUTPUT_BUCKET_NAME: !Ref OutputS3Bucket