name: Sandbox

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  lint:
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint

  deploy-resources:
    name: Deploy SAM Resources
    needs: [lint]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/shared-deploy.yaml
    with:
      WORKFLOW_ENV: qa
    secrets: inherit
