name: Sandbox

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy-resources:
    name: Deploy SAM Resources
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/shared-deploy.yaml
    with:
      WORKFLOW_ENV: qa
    secrets: inherit
